### ISSUE TITLE
pandoc 3.X support

### ISSUE THREAD

**Issue by maralorn** [srid/emanote#455]
During our stackage LTS bump in nixpkgs I have so far fixed all dependencies for emanote here: https://github.com/maralorn/nixpkgs/commit/b27e768e910695d06da62aeffc084f26bea04e8f

Now unsurprisingly emanote fails to build with pandoc 3.1. This is a bit problematic because pinning pandoc to <= 2.9.X on LTS 21 is not feasible.

You can see the first of likely more errors here:

```
emanote> [ 9 of 48] Compiling Emanote.Model.Note.Filter ( src/Emanote/Model/Note/Filter.hs, dist/build/Emanote/Model/Note/Filter.o, dist/build/Emanote/Model/Note/Filter.dyn_o )
emanote> 
emanote> src/Emanote/Model/Note/Filter.hs:41:33: error:
emanote>     • Couldn't match expected type: pandoc-3.0.1:Text.Pandoc.Class.PandocIO.PandocIO
emanote>                                       Pandoc
emanote>                   with actual type: Pandoc -> m0 Pandoc
emanote>     • Probable cause: ‘PF.applyFilters’ is applied to too few arguments
emanote>       In the second argument of ‘($)’, namely
emanote>         ‘PF.applyFilters def filters ["markdown"] x’
emanote>       In the first argument of ‘liftIO’, namely
emanote>         ‘(runIOCatchingErrors
emanote>             $ PF.applyFilters def filters ["markdown"] x)’
emanote>       In the first argument of ‘(>>=)’, namely
emanote>         ‘liftIO
emanote>            (runIOCatchingErrors $ PF.applyFilters def filters ["markdown"] x)’
emanote>    |
emanote> 41 |   liftIO (runIOCatchingErrors $ PF.applyFilters def filters ["markdown"] x) >>= \case
emanote>    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
emanote> 
emanote> src/Emanote/Model/Note/Filter.hs:41:53: error:
emanote>     • Couldn't match expected type ‘PF.Environment’
emanote>                   with actual type ‘[PF.Filter]’
emanote>     • In the second argument of ‘PF.applyFilters’, namely ‘filters’
emanote>       In the second argument of ‘($)’, namely
emanote>         ‘PF.applyFilters def filters ["markdown"] x’
emanote>       In the first argument of ‘liftIO’, namely
emanote>         ‘(runIOCatchingErrors
emanote>             $ PF.applyFilters def filters ["markdown"] x)’
emanote>    |
emanote> 41 |   liftIO (runIOCatchingErrors $ PF.applyFilters def filters ["markdown"] x) >>= \case
emanote>    |                                                     ^^^^^^^
emanote> 
emanote> src/Emanote/Model/Note/Filter.hs:41:74: error:
emanote>     • Couldn't match expected type ‘[String]’ with actual type ‘Pandoc’
emanote>     • In the fourth argument of ‘PF.applyFilters’, namely ‘x’
emanote>       In the second argument of ‘($)’, namely
emanote>         ‘PF.applyFilters def filters ["markdown"] x’
emanote>       In the first argument of ‘liftIO’, namely
emanote>         ‘(runIOCatchingErrors
emanote>             $ PF.applyFilters def filters ["markdown"] x)’
emanote>    |
emanote> 41 |   liftIO (runIOCatchingErrors $ PF.applyFilters def filters ["markdown"] x) >>= \case
emanote>    |                                                                          ^
```

**Comment by srid** [comment]
Yes, we gotta migrate. I'll promptly accept any PR on this, followed by a release even.
